// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttryzuhvnngrdswnsshd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cnl6dWh2bm5ncmRzd25zc2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTU2MTUsImV4cCI6MjA1MjYzMTYxNX0.F6W6WG_EoSywYAdLv6MwICbvgKSqa1KSj8m8Sh8mElk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);